spring:
  application:
    name: users

server:
  port: ${PORT:8080}

app:
  aws:
    region: ${REGION:us-east-1}
    cognito:
      clientId: ${CLIENT_ID:client-id}
      poolId: ${POOL_ID:pool-id}





