kind: Service
apiVersion: v1
metadata:
  name: users
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-tags: "Name=users-service-nlb-eks"
  labels:
    app: users
spec:
  ports:
    - port: 80
      targetPort: users
  selector:
    app: users
  type: LoadBalancer