kind: Deployment
apiVersion: apps/v1
metadata:
  name: users
  labels:
    app: users
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: 926033837002.dkr.ecr.us-east-1.amazonaws.com/users:latest
#          command: ["java", "-jar", "users-0.0.1-SNAPSHOT.jar", "--debug"]
          imagePullPolicy: Always
          ports:
            - name: users
              containerPort: 9000
#          resources:
#            limits:
#              memory: 128M
#              cpu: 50m
#            requests:
#              memory: 128M
#              cpu: 50m
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5