kind: Service
apiVersion: v1
metadata:
  name: votes
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-tags: "Name=votes-service-nlb-eks"
  labels:
    app: votes
spec:
  ports:
    - port: 80
      targetPort: votes
  selector:
    app: votes
  type: LoadBalancer