kind: Deployment
apiVersion: apps/v1
metadata:
  name: votes
  labels:
    app: votes
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: votes
  template:
    metadata:
      labels:
        app: votes
    spec:
      containers:
        - name: votes
          image: 926033837002.dkr.ecr.us-east-1.amazonaws.com/votes:latest
          imagePullPolicy: Always
#          command: ["java", "-jar", "votes-0.0.1-SNAPSHOT.jar", "--debug"]
          ports:
            - name: votes
              containerPort: 9002
          resources:
            limits:
              memory: 2G
              cpu: 1000m
            requests:
              memory: 2G
              cpu: 1000m
          readinessProbe:
            tcpSocket:
              port: 9002
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9002
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5